### ISSUE TITLE
Usage guide

### ISSUE THREAD

**Issue by CreaRo** [tananaev/adblib#1]
A usage guide would be really helpful here! I've been trying to understand the sort of commands I can send across, and am struggling. 
Say I need to call a binary in a remote adb device. How would I do so? 
Essentially all I want to do is call the following ->

1. connect via adb.
2. call ./path/to/my_binary

**Comment by tananaev** [comment]
You can check this for usage example:

[RemoteReader.java](https://github.com/tananaev/rootless-logcat/blob/master/app/src/main/java/com/tananaev/logcat/RemoteReader.java)

ADB protocol documentation might be useful as well:

[protocol.txt](https://android.googlesource.com/platform/system/core/+/master/adb/protocol.txt)

**Comment by CreaRo** [comment]
Thanks!

**Comment by Bilb** [comment]
Hi, I am trying to do the same as you, but I cannot understand how the RemoteReader example helped you ?
