### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by sampalmer** [tananaev/adblib#13]
Hi,

Just wondering if you have any plans to release a new version with the latest changes?

Thanks

**Comment by GiviMAD** [comment]
Also waiting for the latest changes to be available on maven. @tananaev pinning you in case you are not aware of this topic. Thanks in advance!

**Comment by GiviMAD** [comment]
Also waiting for the latest changes to be available on maven. @tananaev pinning you just in case you are not aware of this topic. Thanks in advance!

**Comment by tananaev** [comment]
Released v1.3.
