### ISSUE TITLE
Wireless Debugging

### ISSUE THREAD

**Issue by MuntashirAkon** [tananaev/adblib#14]
Android 11 introduces wireless debugging which greatly simplifies the process of using ADB. However, before making the ADB connection, it needs an additional pairing, meaning it needs extra work to make the pairing first.

**Comment by MuntashirAkon** [comment]
https://github.com/aosp-mirror/platform_system_core/commit/d85f5c013089d569a6274ae5ab01cfaa613fc872#diff-56d178362713a12fd15fb16d425cea35ca7823cd9726c06b03b93d651a731950

**Comment by mirfatif** [comment]
I haven't viewed the code but I think the RSA key authentication is replaced with Bluetooth-like pairing code authentication. And the manual `adb tcpip` step is now handled by OS. The rest is the same.

**Comment by MuntashirAkon** [comment]
Looking at the source, `pairing_auth.cpp` relies on BoringSSL which has licensing issues. I'm currently trying to port the relevant parts (mostly `spake25519`) in Java. So, this might take some time.

**Comment by MuntashirAkon** [comment]
After almost four days of hard work, I was finally able to implement the Spake25519 protocol in pure Java! It will be available shortly at https://github.com/MuntashirAkon/spake2-java. Beware that the Java implementation will be slower than the native implementation. But I've planned to support both native and Java depending on what is available, native will be preferred. But for now, it's only in Java.

**Comment by mirfatif** [comment]
Good advancement. Appreciated.
Shizuku also has a native implementation.

**Comment by MuntashirAkon** [comment]
> Shizuku also has a native implementation.

Yes, they've implemented it based on the AOSP source code (linked above). The trouble is it relies on BoringSSL which has the OpenSSL license (among others), making it incompatible with (A)GPL licenses. Therefore, it would require adding an exception to the (A)GPL license (which is bad). Another issue is that the size of BoringSSL binary after applying optimisations is around 350 KB which means for four platforms, the total size would be around 1.4 MB! Spake2 is probably the smallest implementation and would cost around 100 KB for these four platforms. When implemented in Java, it would take even less size but with a slight performance issue (which might be fixed later on).

**Comment by mirfatif** [comment]
> is around 350 MB

😲 350 KB

> When implemented in Java, it would take even less size but with a slight performance issue

Performance won't be a big issue. Calls to ADB connection APIs aren't very frequent.

**Comment by AsimovGod** [comment]
How long does it take to enable local opening without PC?

**Comment by MuntashirAkon** [comment]
I've created a separate library based on this library and with additional changes including the support for TLS 1.3 and wireless debugging.

https://github.com/MuntashirAkon/libadb-android

This is currently under GPL because [Spake2](https://github.com/MuntashirAkon/spake2-java) is under GPL which will be removed once the GPL dependencies in Spake2 are removed. (As a result, all code in my adb library are actually dual licensed under the terms of Apache-2.0 and GPL-3.0-or-later so that I can make the change in the future.)

You can try the example app there which is a working version of ADB shell (needs a few tweaks though in order to make it more vibrant but I'm considering a separate project for that). A README will also be available very soon. You should be able to use the library from https://jitpack.io.

**Comment by mirfatif** [comment]
Great contribution. Appreciated.
