### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by sampalmer** [tananaev/adblib#6]
Hi,

Firstly, thanks for making this library available through Gradle.

I'm using this library in a new project and would like to add a number of enhancements to the library. But before I do the coding and pull requests, I want to run them by you to make sure we're on the same page.

Enhancements I want to make are:
1. `AdbConnection.openStreams` is a regular `HashMap` but has a race condition when read from the connection thread and updated from main thread at the same time. I'm thinking of changing it to a `ConcurrentHashMap` or possibly adding some locks in the code that accesses it.
1. Add timeout parameter to `AdbConnection.connect()` since this method will never return in the following situations:
    * The auth popup appears on the target device and the protocol version is `0x01000000`
    * The auth popup appears on the target device but is cancelled by the user
    * The auth popup appears on the target device but the user ignores it
1. Add an option to `AdbConnection.connect()` to throw an `AdbAuthenticationFailedException` if we receive a second `AUTH` message after we've already sent our signature. This way we get instant feedback about whether we are "always allowed" from a previous auth attempt, and this is exactly how the `adb` command line tool handles the situation. (The `adb` tool assumes authentication failed in this situation, but then if the user accepts the auth popup and the `adb` tool receives a subsequent `CNXN`, then it changes its mind and decides the connection was ok after all.) Or the other option is, instead of throwing an exception, to at least provide status updates about the current state (eg connecting vs authenticating vs connected) so our app can respond to them in real-time.
1. Update client protocol version from `0x01000000` to `0x01000001`. The main benefit of this is, when the target device gets an auth popup, then when the user presses the "OK" button, then we receive a `CNXN` message and the connection establishes. Whereas if we're on the old version, then we never receive a `CNXN` message when the user presses "OK", so connection attempts always fail unless the user has previously checked the "always allow" box on the auth popup.

This is based on testing against an NVIDIA Shield TV Pro 2019 and Google Pixel 3 XL. Maybe older Android devices that run the older `0x01000000` protocol version have less issues?

Can you let me know what you think of these ideas? And do you need unit tests or any other specific checks and balances before I raise the pull request?

Lastly, how long would the review and release process take before the changes are live and ready to pull into an app through Gradle?

Thanks!

**Comment by tananaev** [comment]
Ideas sound good to me. Please make sure to make small PRs for each change, so it can be easily reviewed.

**Comment by sampalmer** [comment]
Will do!

Just regarding upgrading the protocol version, after further testing, it looks like the hanging connection issue wasn't related to protocol version after all, so I'll leave it at the original version.

**Comment by sampalmer** [comment]
Raised #7 for the thread safety issues

**Comment by sampalmer** [comment]
Raised #9 for timeout option

**Comment by sampalmer** [comment]
Raised #10 for auth exception

**Comment by sampalmer** [comment]
Closing this issue since it's been converted to pull requests

**Comment by mirfatif** [comment]
@tananaev  @sampalmer may I merge recent PRs to `com.cgutman.adblib` (https://github.com/mirfatif/AdbLib)?

**Comment by sampalmer** [comment]
> @tananaev @sampalmer may I merge recent PRs to `com.cgutman.adblib` (https://github.com/mirfatif/AdbLib)?

Sure!

I just looked at your fork and noticed you have a fix for `AdbStream.read()`: https://github.com/mirfatif/AdbLib/commit/aaa08a4bd4567bbf7a03f09f22fddbd5c256498e.

Does that fix the issue where code like this sometimes fails?

```java
try (AdbStream stream = connection.open("shell:echo Hello world")) {
    byte[] response = stream.read();
    String responseText = new String(response, StandardCharsets.UTF_8);
    Assert.assertEquals("Hello world", responseText.trim());
}
```

**Comment by mirfatif** [comment]
> Sure!

Thanks.

> Does that fix the issue where `read()` sometimes fails with an `IOException` instead of sending back the response text?
> 
> ```java
> try (AdbStream stream = connection.open("shell:echo Hello world")) {
>     byte[] response = stream.read();
>     String responseText = new String(response, StandardCharsets.UTF_8);
>     Assert.assertEquals("Hello world", responseText.trim());
> }
> ```

While waiting for `read()` ([here](https://github.com/mirfatif/AdbLib/blob/5a8cd972c64e85a04753a2b5a8561124441148ed/src/main/java/com/cgutman/adblib/AdbStream.java#L120)), if `isClosed` is set true ([here](https://github.com/mirfatif/AdbLib/blob/5a8cd972c64e85a04753a2b5a8561124441148ed/src/main/java/com/cgutman/adblib/AdbStream.java#L96)), `read()` would throw Exception ([here](https://github.com/mirfatif/AdbLib/blob/5a8cd972c64e85a04753a2b5a8561124441148ed/src/main/java/com/cgutman/adblib/AdbStream.java#L124)) even if `readQueue` is still receiving stdout/stderr data ([here](https://github.com/mirfatif/AdbLib/blob/5a8cd972c64e85a04753a2b5a8561124441148ed/src/main/java/com/cgutman/adblib/AdbStream.java#L55)) and we have one or more messages to be `read()` and displayed yet.
I hope this makes sense :smile: 

So the following would definitely throw IOException on first `read()` without printing anything:
```
try (AdbStream stream = connection.open("shell:echo Hello world")) {
    SystemClock.sleep(1000);
    byte[] response = stream.read();
    System.out.println(new String(response, StandardCharsets.UTF_8).trim());
}
```
I've tried to fix this.

**Comment by sampalmer** [comment]
> While waiting for `read()` ([here](https://github.com/mirfatif/AdbLib/blob/5a8cd972c64e85a04753a2b5a8561124441148ed/src/main/java/com/cgutman/adblib/AdbStream.java#L120)), if `isClosed` is set true ([here](https://github.com/mirfatif/AdbLib/blob/5a8cd972c64e85a04753a2b5a8561124441148ed/src/main/java/com/cgutman/adblib/AdbStream.java#L96)), `read()` would throw Exception ([here](https://github.com/mirfatif/AdbLib/blob/5a8cd972c64e85a04753a2b5a8561124441148ed/src/main/java/com/cgutman/adblib/AdbStream.java#L124)) even if `readQueue` is still receiving stdout/stderr data ([here](https://github.com/mirfatif/AdbLib/blob/5a8cd972c64e85a04753a2b5a8561124441148ed/src/main/java/com/cgutman/adblib/AdbStream.java#L55)) and we have one or more messages to be `read()` and displayed yet.
> I hope this makes sense 😄

Ah, yeah that makes sense thanks! I've been running into this bug as well, but I hadn't realised why it was happening until I saw your fix!

I've just raised #11 to get this fixed in `com.tananaev.adblib` as well. I implemented the fix without changing the API to keep things simple for existing apps that use code like this:

```java
while (!stream.isClosed()) {
    stream.read();
    // etc
}
```
